### ISSUE TITLE
Submission UI and duplicated upload

### ISSUE THREAD

**Issue by nik-sm** [XiaoxiWei/NeurIPS_BEETL#3]
Hello,

I tried (unsuccessfully) to submit several times (maybe ~5 tries), before realizing that the required submission format is "answer.txt.zip".

However - I then made 1 submission, including a description message - but the UI recorded this as 3 submissions within 1 second of each other (1 including my message and 2 not including, all identical scores).

Can you confirm the exact process I should take to make submissions, and whether there might be some specific things that we should watch out for when trying to upload submissions? 

Thanks!

**Comment by XiaoxiWei** [comment]
Hi, thanks for the question. You could refer to tutorial4 for how to name the file. 'When you upload the txt label file to CodaLab, please rename the txt file as 'answer.txt' and zip it before uploading. ', actually once your txt file is 'answer.txt' then the name of the zip file does not matter.

For the submission process, I think the problem you met is because of network delay. I'm not able to reproduce it, but try to submit once, wait for a while, then press the refresh button. Sometimes for showing the score after it's computed you need to refresh the page.

Hope that helps!

**Comment by XiaoxiWei** [comment]
closed issue
